package com.xiaoyitong.app.dao;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface StudentTemperatureMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student_temperature
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Integer studentId);
//
////    /**
////     * This method was generated by MyBatis Generator.
////     * This method corresponds to the database table student_temperature
////     *
////     * @mbggenerated
////     */
////    int insert(StudentTemperature record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student_temperature
//     *
//     * @mbggenerated
//     */
//    int insertSelective(StudentTemperature record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student_temperature
//     *
//     * @mbggenerated
//     */
//    StudentTemperature selectByPrimaryKey(Integer studentId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student_temperature
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKeySelective(StudentTemperature record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table student_temperature
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(StudentTemperature record);
}
