package com.xiaoyitong.app.dao;

import com.xiaoyitong.app.pojo.StudentInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Date;
@Mapper
@Component
public interface StudentInfoMapper {

    @Select("select * from student_info where teacher_id=#{tid}")
    public List<StudentInfo> getByTeacherid(@Param("tid")Integer teacher_id);

    @Select("select * from student_info where  teacher_id=#{teacher_id} and departments=#{departments} and major=#{major} " +
            " and grade=#{grade} and myclass={myclass}")
    public List<StudentInfo> getbyTDMGM(StudentInfo studentInfo);

    @Select("select * from student_info where  teacher_id=#{teacher_id} and departments=#{departments} and major=#{major} " +
            " and grade=#{grade}")
    public List<StudentInfo> getbyTDMG(StudentInfo studentInfo);

    @Select("select * from student_info where  teacher_id=#{teacher_id} and departments=#{departments} and major=#{major} ")
    public List<StudentInfo> getbyTDM(StudentInfo studentInfo);

    @Select("select * from student_info where  teacher_id=#{teacher_id} and departments=#{departments}")
    public List<StudentInfo> getbyTD(StudentInfo studentInfo);

    StudentInfo selectByPrimaryKey(Integer studentId); // 查询学号对应的学生

    @Select("select * from student_info where  teacher_id=#{teacher_id} and name=#{name}")
    public List<StudentInfo> getbyID(StudentInfo studentInfo);

    @Select("select * from student_info where  student_id=#{student_id} and teacher_id=#{teacher_id} ")
    public List<StudentInfo> getbyname(StudentInfo studentInfo);

    @Select("select * from student_info where  dormitory_id=#{dormitory_id} and teacher_id=#{teacher_id}")
    public List<StudentInfo> getbydormitory(StudentInfo studentInfo);

    @Select("select * from student_info where  address=#{address} and teacher_id=#{teacher_id}")
    public List<StudentInfo> getbyaddress(StudentInfo studentInfo);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    int insert(StudentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    int insertSelective(StudentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentInfo record);
}
