package com.xiaoyitong.app.dao;

import com.xiaoyitong.app.pojo.StudentLeave;
import com.xiaoyitong.app.pojo.StudentLogin;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Mapper
@Component
public interface StudentLoginMapper {

    @Update("update student_login set password=#{password}  where phone=#{phone}")
    int updatePasswordByPhone(Integer phone,String password);

    @Select("select phone from student_login where " +
            " phone=#{phone}")
    int selectPhone(Integer phone);

    @Select("select * from student_login where " +
            " phone=#{phone}")
    StudentLogin selectByPhone(Integer phone);

    @Select("select student_id from student_login where " +
            " student_id=#{studentID}")
    int selectStudentID(Integer studentID);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_login
     *
     * @mbggenerated
     */
    int insert(StudentLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_login
     *
     * @mbggenerated
     */
    int insertSelective(StudentLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_login
     *
     * @mbggenerated
     */
    StudentLogin selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentLogin record);
}
