package com.xiaoyitong.app.dao;

import com.xiaoyitong.app.pojo.StudentDormitory;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface StudentDormitoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_dormitory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer dormitoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_dormitory
     *
     * @mbggenerated
     */
    int insert(StudentDormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_dormitory
     *
     * @mbggenerated
     */
    int insertSelective(StudentDormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_dormitory
     *
     * @mbggenerated
     */
    StudentDormitory selectByPrimaryKey(Integer dormitoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_dormitory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentDormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_dormitory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentDormitory record);
}
