package com.xiaoyitong.app.dao;

import com.xiaoyitong.app.pojo.StudentStatues;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Mapper
@Component
public interface StudentStatuesMapper {
    /**
     * This method was generated by Noah
     *
     * @mbggenerated
     */
    @Select("select * from student_statues where student_id=#{student_id}")
    List<StudentStatues> selectById(@Param("student_id") Integer student_id);

    @Select("select student_statues.*,teacher_info.`name` instructor from student_statues,teacher_info where " +
            " DATE_SUB(#{date}, INTERVAL 1 DAY) <= date(date)" +
            " and student_id=#{studentID}")
    List<StudentStatues> selectByDay(Integer studentID, Date date);

    @Select("select student_statues.*,teacher_info.`name` instructor from student_statues,teacher_info  where " +
            "DATE_SUB(#{date}, INTERVAL 7 DAY) <= date(date) " +
            " and student_id=#{studentID}")
    List<StudentStatues> selectByWeek(Integer studentID, Date date);

    @Select("select student_statues.*,teacher_info.`name` instructor from student_statues,teacher_info  where " +
            "DATE_SUB(#{date}, INTERVAL 1 MONTH) <= date(date) " +
            " and student_id=#{studentID}")
    List<StudentStatues> selectByMonth(Integer studentID, Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_statues
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_statues
     *
     * @mbggenerated
     */
    int insert(StudentStatues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_statues
     *
     * @mbggenerated
     */
    int insertSelective(StudentStatues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_statues
     *
     * @mbggenerated
     */
    StudentStatues selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_statues
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentStatues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_statues
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentStatues record);
}
