package com.xiaoyitong.app.dao;

import com.xiaoyitong.app.pojo.StudentReport;
import com.xiaoyitong.app.pojo.StudentReportKey;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface StudentReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(StudentReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    int insert(StudentReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    int insertSelective(StudentReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    StudentReport selectByPrimaryKey(StudentReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentReport record);
}
