package com.xiaoyitong.app.dao;

import com.xiaoyitong.app.pojo.StudentException;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface StudentExceptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_exception
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_exception
     *
     * @mbggenerated
     */
    int insert(StudentException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_exception
     *
     * @mbggenerated
     */
    int insertSelective(StudentException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_exception
     *
     * @mbggenerated
     */
    StudentException selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_exception
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentException record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_exception
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentException record);
}
