package com.xiaoyitong.app.dao;

import com.xiaoyitong.app.pojo.TeacherLogin;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface TeacherLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbggenerated
     */
    int insert(TeacherLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbggenerated
     */
    int insertSelective(TeacherLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbggenerated
     */
    TeacherLogin selectByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeacherLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeacherLogin record);
}
