package com.xiaoyitong.app.pojo;

import lombok.Data;

@Data
public class StudentLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_login.student_id
     *
     * @mbggenerated
     */
    private Integer student_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_login.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_login.phone
     *
     * @mbggenerated
     */
    private Integer phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_login.student_id
     *
     * @return the value of student_login.student_id
     *
     * @mbggenerated
     */
    public Integer getStudent_id() {
        return student_id;
    }

    public void setStudent_id(Integer student_id) {
        this.student_id = student_id;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getPhone() {
        return phone;
    }

    public void setPhone(Integer phone) {
        this.phone = phone;
    }
}
