package com.xiaoyitong.app.pojo;

import lombok.Data;

@Data
public class StudentDormitory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_dormitory.dormitory_id
     *
     * @mbggenerated
     */
    private Integer dormitory_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_dormitory.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_dormitory.student_id
     *
     * @mbggenerated
     */
    private Integer student_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_dormitory.dormitory_id
     *
     * @return the value of student_dormitory.dormitory_id
     *
     * @mbggenerated
     */
    public Integer getDormitory_id() {
        return dormitory_id;
    }

    public void setDormitory_id(Integer dormitory_id) {
        this.dormitory_id = dormitory_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStudent_id() {
        return student_id;
    }

    public void setStudent_id(Integer student_id) {
        this.student_id = student_id;
    }
}
