package com.xiaoyitong.app.pojo;

public class StudentReportKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.student_id
     *
     * @mbggenerated
     */
    private Integer student_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_report.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacher_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_report.student_id
     *
     * @return the value of student_report.student_id
     * @mbggenerated
     */
    public Integer getStudent_id() {
        return student_id;
    }

    public void setStudent_id(Integer student_id) {
        this.student_id = student_id;
    }

    public Integer getTeacher_id() {
        return teacher_id;
    }

    public void setTeacher_id(Integer teacher_id) {
        this.teacher_id = teacher_id;
    }
}
