package com.xiaoyitong.app.pojo;

import lombok.Data;

import java.util.Date;
@Data
public class StudentStatues {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_statues.student_id
     *
     * @mbggenerated
     */
    private Integer student_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_statues.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_statues.body
     *
     * @mbggenerated
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_statues.temperature
     *
     * @mbggenerated
     */
    private Double temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_statues.statues
     *
     * @mbggenerated
     */
    private String statues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_statues.date
     *
     * @mbggenerated
     */
    private Date date;

    public Integer getStudent_id() {
        return student_id;
    }

    public void setStudent_id(Integer student_id) {
        this.student_id = student_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Double getTemperature() {
        return temperature;
    }

    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    public String getStatues() {
        return statues;
    }

    public void setStatues(String statues) {
        this.statues = statues;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
}
