package com.xiaoyitong.app.pojo;

import lombok.Data;

import java.util.Date;
@Data
public class StudentTemperature {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_temperature.student_id
     *
     * @mbggenerated
     */
    private Integer student_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_temperature.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_temperature.temperature
     *
     * @mbggenerated
     */
    private Double temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_temperature.photo
     *
     * @mbggenerated
     */
    private Integer photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_temperature.date
     *
     * @mbggenerated
     */
    private Date date;

    public Integer getStudent_id() {
        return student_id;
    }

    public void setStudent_id(Integer student_id) {
        this.student_id = student_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getTemperature() {
        return temperature;
    }

    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    public Integer getPhoto() {
        return photo;
    }

    public void setPhoto(Integer photo) {
        this.photo = photo;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
}
