package com.xiaoyitong.app.pojo;

import lombok.Data;

@Data
public class TeacherInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacher_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.phone
     *
     * @mbggenerated
     */
    private Integer phone;

    public Integer getTeacher_id() {
        return teacher_id;
    }

    public void setTeacher_id(Integer teacher_id) {
        this.teacher_id = teacher_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPhone() {
        return phone;
    }

    public void setPhone(Integer phone) {
        this.phone = phone;
    }
}
